# GPU := B200
# SRC := 01_naive_shared_float.cu
# OUT := 01_naive_shared_float.out
# CMD := ./01_naive_shared_float.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 02_naive_shared_bf16.cu
# OUT := 02_naive_shared_bf16.out
# CMD := ./02_naive_shared_bf16.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 03_tma_testing.cu
# OUT := 03_tma_testing.out
# CMD := ./03_tma_testing.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 04_tensorcores.cu
# OUT := 04_tensorcores.out
# CMD := ./04_tensorcores.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 05_tc_swizzle.cu
# OUT := 05_tc_swizzle.out
# CMD := ./05_tc_swizzle.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 06_pipelining.cu
# OUT := 06_pipelining.out
# CMD := ./06_pipelining.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 07_warp_specialization.cu
# OUT := 07_warp_specialization.out
# CMD := ./07_warp_specialization.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 08_cluster_mma.cu
# OUT := 08_cluster_mma.out
# CMD := ./08_cluster_mma.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 09_persistent_static.cu
# OUT := 09_persistent_static.out
# CMD := ./09_persistent_static.out
# CONFIG := standalone
# include ../common.mk

GPU := B200
SRC := 09_b_persistent_static.cu
OUT := 09_b_persistent_static.out
CMD := ./09_b_persistent_static.out
CONFIG := standalone
include ../common.mk

# GPU := B200
# SRC := 10_clc.cu
# OUT := 10_clc.out
# CMD := ./10_clc.out
# CONFIG := standalone
# include ../common.mk

# GPU := B200
# SRC := 12_clc_cluster_test.cu
# OUT := 12_clc_cluster_test.out
# CMD := ./12_clc_cluster_test.out
# CONFIG := standalone
# include ../common.mk


